version: '3'
services:
  database:
    image: mariadb:latest
    container_name: database
    hostname: database
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: alpha
      MARIADB_USER: alpha_web
      MARIADB_PASSWORD: password
    volumes:
      - ./db-exports:/docker-entrypoint-initdb.d:rw
    networks:
      - alpha-docker
  database_admin:
    depends_on:
      - database
    image: phpmyadmin:latest
    container_name: database_admin
    hostname: database_admin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - alpha-docker
  webserver:
    depends_on:
      - database
      - database_admin
    image: webdevops/php-apache:8.3
    container_name: webserver
    hostname: webserver
    ports:
      - 80:80
    volumes:
      - ../static:/var/www/html/static:rw
      - ../platform:/var/www/html/platform:rw
      - ../app:/var/www/html/app:rw
      - ./apache-exports/sites-enabled:/etc/apache2/sites-enabled:rw
      - ./platform-exports/webserver/set-permissions.sh:/var/www/set-permissions.sh
    # command: /bin/sh -c /var/www/set-permissions.sh
    networks:
      - alpha-docker
networks:
  alpha-docker:
    driver: bridge