version: '3.7'
services:
  platform:
    build:
      args:
        user: web
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.3-fpm-alpine
    container_name: platform
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../static:/var/www/static:rw
      - ../platform:/var/www/platform:rw
      - ../app:/var/www/app:rw
      - ./platform-exports/.env:/var/www/platform/.env
    networks:
      - alpha-mainnet
  db:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: alpha
      MARIADB_USER: alpha_web
      MARIADB_PASSWORD: password
    volumes:
      - ./db-exports:/docker-entrypoint-initdb.d:rw
    networks:
      - alpha-mainnet
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ../static:/var/www/static:rw
      - ../platform:/var/www/platform:rw
      - ../app:/var/www/app:rw
      - ./platform-exports/nginx:/etc/nginx/conf.d/
    networks:
      - alpha-mainnet
networks:
  alpha-mainnet:
    driver: bridge