version: '3.7'
services:
  platform:
    build:
      args:
        user: web
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.3.7RC1-apache-bullseye
    container_name: platform
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../static:/var/www/static:rw
      - ../platform:/var/www/platform:rw
      - ../app:/var/www/app:rw
      - ../docker:/var/www/docker:rw
      - ./platform-exports/webserver/sites/001-alpha.conf:/etc/apache2/sites-available/001-alpha.conf
      - ./platform-exports/webserver/alpha-init.sh:/opt/alpha-init.sh
      - ./platform-exports/php.ini:/usr/local/etc/php/conf.d/overrides.ini
      - ./platform-exports/config.env:/var/www/platform/.env
    networks:
      - alpha-mainnet
    entrypoint: [ "/bin/bash", "/opt/alpha-init.sh" ]
  db:
    image: mariadb:latest
    container_name: database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: alpha
      MARIADB_USER: alpha_web
      MARIADB_PASSWORD: password
    volumes:
      - ./db-exports:/docker-entrypoint-initdb.d:rw
    networks:
      - alpha-mainnet
networks:
  alpha-mainnet:
    driver: bridge
